"""Add Review Model

Revision ID: 8d62433fa163
Revises: 8d6ce69bc904
Create Date: 2023-09-05 20:22:11.617150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d62433fa163'
down_revision = '8d6ce69bc904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
